language: node_js
node_js:
  - "10"
addons:
  postgresql: "9.4"
env:
  DATABASE_URL: postgres://postgres@localhost/mosaic_dev
  USING_DOCKER: true

install:
  - cd client
  - yarn
  - cd ../server
  - yarn
  - cd ..

script:
  - cd server
  - yarn lint
  - yarn db:create
#  - yarn test:ci
  - yarn db:reset
  - yarn start & node_modules/.bin/wait-on -t 30000 tcp:localhost:8080
  - node_modules/.bin/apollo service:push --endpoint http://localhost:8080/graphql --tag=$TRAVIS_BRANCH --key="service:mosaic:hGCwzWa_wg71SWpJ7NBMoA"
  - cd ../client
  - yarn lint
  - yarn test
  - yarn start & node_modules/.bin/wait-on -t 30000 http://localhost:3000/
#  - yarn test:cypress
